data:
  imageoptimizer:
    original_size: 502099
    current_size: 138366
  blurhash: LBQ0O0Eh00OX3sxBI;sl00M|.6oK
  dominant_color: '#ffffff'
size: 138366
last_modified: 1619383863
width: 1367
height: 1052
mime_type: image/png
