data:
  imageoptimizer:
    original_size: 546025
    current_size: 152215
  blurhash: 'L8O:#4AE00Os3ZxAEMxY00Ip-.n$'
  dominant_color: '#fbfbfb'
size: 152215
last_modified: 1619383866
width: 1367
height: 1052
mime_type: image/png
